### ISSUE TITLE
Requesting help for Linux Build with ASSDraw3

### ISSUE THREAD

**Issue by heptahex** [wangqr/Aegisub#112]
I, recently built for my Linux machine from source using the guide on the repo's homepage. Everything works well but I still don't understand why both Official Aegisub and this fork don't contain ASSDraw3 in Linux build. Did I miss something else in building Aegisub? If I missed something how can I fix it. Thanks.

**Comment by wangqr** [comment]
ASSDraw3 depends on [`agg`](https://antigrain.com/), which is dead for a long time. Building a working ASSDraw3 won't be straightforward, it may need some fixes in the code.

**Comment by heptahex** [comment]
Ok. I get it. Thank you.

**Comment by TheOneric** [comment]
To elaborate a bit on the state of AssDraw:
The latest commit to Aegisub/AssDraw was in 2012, there was a [fork by biki-desu](https://github.com/biki-desu/assdraw) in 2014 which makes it (somewhat) work with wxGTK *(wxGTK from 2014 that is)*.

With the **GTK2** version of wxWidgets-3.0 it mostly works, nodes are rendered and the draw command can be copied to Aegisub, but attempting to set a background image leads to errors and eventhough something from the image gets rendered it doesn't react to zooming and panning, so it cannot be used for accurate positioning. *(GTK2 is by now no longer supported.)*
With the **GTK3** version however, not even the drawing nodes get rendered.

At one point, I intented to make an attempt to at least make the image work correctly in GTK2, but gave up and only fixed some build-related things and the incorrect license info. If someone considers this to be worth the time and wants to take a stab at this, here's a zipped bare git repo including biki-desu's GTK changes and my minor fixes: [assdraw_bare-git.zip](https://github.com/wangqr/Aegisub/files/6873059/assdraw_bare-git.zip) *(either `git clone assdraw/.git assdraw_work` after unzipping, or run `git reset --hard HEAD` inside the unzipped assdraw directory to get all working files)*

However, if the panning and zooming PR get's merged in Aegisub upstream, considering that Aegisub already has tools for vector clipping, it may perhaps be easier and better to add a vector *drawing* tool to Aegisub itself, instead of updating AssDraw.
