### ISSUE TITLE
Aegisub does not open anymore in Arch with boost 1.76.0

### ISSUE THREAD

**Issue by MinatoKamikaze** [wangqr/Aegisub#113]
I had installed your build of Aegisub from AUR but Aegisub suddenly stopped working in Arch Linux after I updated the system. When I tried to open it through the terminal, it gave the following error:

> aegisub: error while loading shared libraries: libboost_filesystem.so.1.75.0: cannot open shared object file: No such file or directory

I then downgraded boost from version 1.76.0 to 1.75.0. Aegisub started working but other software like Inkscape stopped working.
How can I fix this?

**Comment by wangqr** [comment]
Have you tried rebuild the AUR after upgrading boost?

**Comment by MinatoKamikaze** [comment]
I just tried but it failed. This is the error I received.

```/usr/bin/ld: CMakeFiles/Aegisub.dir/src/search_replace_engine.cpp.o: undefined reference to symbol '_ZN6icu_698Collator14createInstanceERKNS_6LocaleER10UErrorCode'
/usr/bin/ld: CMakeFiles/Aegisub.dir/src/search_replace_engine.cpp.o: undefined reference to symbol '_ZN6icu_698Collator14createInstanceERKNS_6LocaleER10UErrorCode'
/usr/bin/ld: /usr/lib/libicui18n.so.69: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/Aegisub.dir/build.make:3322: aegisub] Error 1
make[1]: *** [CMakeFiles/Makefile2:158: CMakeFiles/Aegisub.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in package().
    Aborting...
error making: aegisub-wangqr-git

**Comment by wangqr** [comment]
c9d8529aff5cb8db2d9a9af7b5cf594b5a762818 should fix the missing symbol error.

However this shouldn't be necessary, because `_ZN6icu_698Collator14createInstanceERKNS_6LocaleER10UErrorCode` (aka `icu_69::Collator::createInstance(icu_69::Locale const&, UErrorCode&)`) is introduced indirectly via [Boost::Regex](https://github.com/boostorg/regex/blob/86f82635d4eb483be1b5cb72820dcf998cec48be/include/boost/regex/v5/icu.hpp#L54) and linking to Boost::Regex should have included its dependencies.

**Comment by MinatoKamikaze** [comment]
That worked. I can build it now. Thank you very much.
