### ISSUE TITLE
macOS的多声道支持 | OpenAL (macOS) player does not support multi-channel output

### ISSUE THREAD

**Issue by Yang-Xijie** [wangqr/Aegisub#118]
请问macOS支持多声道吗？
我下载的最新的release v3.3.2 https://github.com/wangqr/Aegisub/releases/tag/v3.3.2

查看设置界面：
<img width="588" alt="image" src="https://user-images.githubusercontent.com/57952362/128604170-862031dd-8cbe-41a4-8e0b-5c1da6a09bdf.png">
音频播放器无法重新选择；关闭downmix。只能听到单声道

https://github.com/wangqr/Aegisub/issues/59#issuecomment-659153737
与此同样，导出后可以听到双声道音频

_Originally posted by @Yang-Xijie in https://github.com/wangqr/Aegisub/issues/59#issuecomment-894664353_

**Comment by wangqr** [comment]
目前XAudio2是唯一支持了多声道的音频播放器（限Windows），macOS不支持多声道。

若要在macOS上支持多声道，需要：
1. 修改目前的OpenAL播放器，添加多声道支持，
2. 考虑到macOS计划废弃OpenAL，更好的方案是写一个新的基于AVAudioEngine的播放器

---

Currently XAudio2 on Windows is the only audio player that has multi-channel output support. To make multi-channel output support work on macOS, either:
1. Add multi-channel to current OpenAL player, or
2. Implement a new audio player using AVAudioEngine, as OpenAL is deprecated since 10.15.

欢迎贡献代码 PR welcome

**Comment by wangqr** [comment]
能麻烦试下#139的产物吗？https://github.com/wangqr/Aegisub/runs/6441945517
![img](https://user-images.githubusercontent.com/8182182/168633325-92830f0e-76da-417f-9ef1-ccedf46d9501.png)

**Comment by Yang-Xijie** [comment]
macOS 12.3 Intel

之前：`Aegisub 3.3.2` -- 没有双声道
现在：`Aegisub 0-(unnamed branch)-cd5cfb2 [DEBUG VERSION]`
在 设置 > 高级 > 音频 中切换音频播放器为 `CoreAudio` **有双声道**！
感谢开发者！
