### ISSUE TITLE
Embedded font may take forever to load

### ISSUE THREAD

**Issue by msg7086** [wangqr/Aegisub#135]
A file with about 800KB size embedded font takes about 4 seconds to load.

A file with about 2000KB size embedded font takes about 34 seconds to load.

A file with about 10MB size embedded font takes forever to load.

Suspecting something inside `ass_parser.cpp` or `ass_attachment.cpp` but I'm not able to debug it. Wondering if someone can take a quick look.

Thanks.

**Comment by Kienyew** [comment]
I suspect this low performance is caused by the inappropriate use case of `boost::flyweight` container in `ass_attachment.h`. (take a read on https://www.boost.org/doc/libs/1_62_0/libs/flyweight/doc/tutorial/index.html)

https://github.com/wangqr/Aegisub/blob/d771fb21af9db95fb174c95549fc765ef39652cd/src/ass_attachment.h#L24-L26

In short, the `boost::flyweight` class save memory on immutable data that might appear in many places of code, but increase overhead when changing them frequently. The performance degradation of loading large attachment probably attributes to the thousands runs of this function:

https://github.com/wangqr/Aegisub/blob/d771fb21af9db95fb174c95549fc765ef39652cd/src/ass_parser.cpp#L108-L131

specifically, at line 125 `attach->AddData(data); `

**Comment by msg7086** [comment]
Aha! I thought it was the flyweight because that's the only thing I don't know and it looks suspicious. Have you tried opening a file to see how fast it is now? Should be nearly instant after the change.

**Comment by Kienyew** [comment]
> Aha! I thought it was the flyweight because that's the only thing I don't know and it looks suspicious. Have you tried opening a file to see how fast it is now? Should be nearly instant after the change.

Yes, I've tested it on a 17MB file and it worked fine ^ω^
