### ISSUE TITLE
大佬能不能build一个win32的版本

### ISSUE THREAD

**Issue by nnothing1** [wangqr/Aegisub#24]
我看您的信息感觉你是中国人所以我就用中文发issue了，
大佬能不能build一个win32的版本 。
我有些脚本和插件用win64版本会导入不了

**Comment by wangqr** [comment]
原本发3.3.0时我想过要不要编译32位版，本质讲没有技术难度，但我开发机硬盘空间不太够所以搁置了。有空我看看把3.3.0编译一份win32好了（每日编译大概率不会有32位版）。

好奇一下具体哪些脚本和插件用win64版本用不了，我寻思lua应该不会存在这个问题，你可能指的是AviSynth+的32位插件？

**Comment by wangqr** [comment]
或者你也可以尝试 https://github.com/cqjjjzr/Aegisub/tree/dev-cj 直接从这个编译，据称是自动解决依赖的

**Comment by nnothing1** [comment]
我也不是很懂这些 插件是一个大佬写的传到我这来了 我看起来是需要读一个dll文件 然后就can't not load the module 不是有效的win32位应用程序

**Comment by wangqr** [comment]
是放进csri文件夹用的么

**Comment by wangqr** [comment]
如果是VSFilterMod的话，请从 https://github.com/sorayuki/VSFilterMod/releases 下载最新版，这玩意多年前就支持win64了

**Comment by nnothing1** [comment]
那不是vsfm，这个我是直接放根目录的，其中出问题的一个脚本是这个https://github.com/qwe7989199/Lyric-Importer-for-Aegisub  的QQMusicCommon.dll

**Comment by wangqr** [comment]
如果只是偶尔使用的话，你可以到 http://www.plorkyeran.com/aegisub/ 下载最后一个win32版本（r8942），保存成 ass 后再用新版打开；
如果经常使用的话，请去那个repo开issue（可以附上这个issue的链接），以探讨是在哪边解决这个问题

PS: 目前（2019年）32bit系统的使用率已经[只有1.2%](https://store.steampowered.com/hwsurvey/)

**Comment by nnothing1** [comment]
也不知道为啥教我做字幕特效的传下来的都是32位的，那我国庆先慢慢自个试试编译一个32位的版本试试。

**Comment by cqjjjzr** [comment]
这一问题已在https://github.com/qwe7989199/Lyric-Importer-for-Aegisub/issues/2 提到过。似乎只能使用32bit版本程序。

**Comment by nnothing1** [comment]
所以我才努力的在想用你的repo尝试编译一个较新的32bit的程序，我还有些也是不支持64bit的脚本。

**Comment by wangqr** [comment]
编译了一版放在 https://ftp.wangqr.tk/aegisub/aegisub-win32-cmake-20191002-r9042.zip ，v3.3.0的32位版应该会稍后搞出来。

我计划在完成32位版3.3.0的编译后关闭此issue，如果仍有问题可以新开issue或者重开这个issue。

**Comment by wangqr** [comment]
Keep in mind that if you use 32-bit builds, you will NOT be able to use more than 4GiB memory, and performance will suffer due to the additional WoW64 emulation layer, and lack of SIMD instructions. The performance impact is especially noticeable in fftw (for audio spectrum) and AviSynth. Unless you are using some legacy tools that either no longer maintained, or for some reason cannot use 64-bit, or you are actually using a 32-bit CPU, please use the 64-bit version.

SSE2 is still REQUIRED to run the 32-bit version.

**Comment by wangqr** [comment]
> 这一问题已在qwe7989199/Lyric-Importer-for-Aegisub#2 提到过。似乎只能使用32bit版本程序。

Lyric-Importer-for-Aegisub 所需的64位dll我已提供，能否提供其它存在问题的插件的列表？

**Comment by nnothing1** [comment]
感谢你的解决，不兼容的dll还剩一个，但是是某个字幕组在做的还没有公开的插件，也是间接的流传到我的这提供不了，非常抱歉。感谢你几天以来的帮助，目前应该没有什么其他的问题了。
