### ISSUE TITLE
Increase in RAM Usage with r9069

### ISSUE THREAD

**Issue by MadokaAyukawa** [wangqr/Aegisub#31]
This may be normal, and I'm fine if that's that case. I thought I'd mention this in case there's an issue.

I'm timing a video, and if I load it into r9069, it uses 1,145.4 MB of RAM. With r8995 (the custom build you made me), it's only 400.8 MB; with 3.3.2, it's 409.5 MB. Same scripts, same computer. That seems like a significant increase in resources, but perhaps that's normal?

**Comment by wangqr** [comment]
Yes, the increase of memory usage is because Aegisub now loads original audio. Previously, Aegisub only load Mono channel int16_t audio. So usually the memory usage will be multiplied by the number of channels in your audio track. You may choose hard disk as the audio cache type in preference, which should lower the memory usage if you are loading audio with high channel count or high bit depth.

**Comment by wangqr** [comment]
Detailed explaination:

First of all, there is a memory leak bug in r9056, and should have been fixed in r9063. If you see the memory usage grows after finished loading the audio, then that could be a bug.

For the change in down-mixing audio, take a 1 hour 44100Hz stereo float32 audio as an example. The audio cache will use
* 3600 * 44100 * 1 * 2 = 303 MiB   in previous version, or
* 3600 * 44100 * 2 * 4 = 1211 MiB   in current version.

This isn't a big issue to me as most of my computers has 8GB+ RAM, and there is also swap if RAM is not enough. And if even swap is not enough, there is still an option to use hard disk cache or no cache, both have decent performance[1]. If this do cause problem for you, please let me know so I can add an option to enable/disable the down-mix in FFMS. As for Avisynth, the default down-mix option is still `ConvertToMono` as before, I just added another `None` option.

I implemented this feature because it useful in my use case (Aegisub/Aegisub#160). In order to play the original audio track, the audio player needs to be `XAudio2`, in case you want to try it out.

　
[1] DirectShowSource in Avisynth is not designed to be able to do random seek. So cache must be turned on (either RAM or HD) when using DirectShowSource in Avisynth. FFmpegSource should work well without cache because FFMS is designed to do random seek by creating an index of the track.

**Comment by MadokaAyukawa** [comment]
Thank you for your explanations. I'm fine as it's working as expected. I will try out the XAudio2 player; I didn't know that you needed to change the player so things seemed the same to me. An option to down-mix may be nice as some may not need the higher fidelity of the original audio depending on what they are subtitling.
