### ISSUE TITLE
开启自动提交所有更改后导致响应卡顿 | Lag when auto commit change in audio panel is on

### ISSUE THREAD

**Issue by The-Asgore** [wangqr/Aegisub#43]
开启“自动提交所有更改”功能后，在音频区框选范围时，响应卡顿，关闭后可恢复正常

**Comment by wangqr** [comment]
卡顿的原因是当移动鼠标时会自动提交，一种可能的方案是仅在松开鼠标时自动提交，而在拖动时不提交，但这样与现有行为差别较大

**Comment by The-Asgore** [comment]
我认为在松开鼠标时自动提交更改是不错的方案，不知知否在其他方面有困难之处

**Comment by wangqr** [comment]
> 不知知否在其他方面有困难之处

没有困难，只需修改以下两处即可：
https://github.com/wangqr/Aegisub/blob/60eae86e21557340dcc0ae45719869e1bac9e4fa/src/audio_display.cpp#L1123
https://github.com/wangqr/Aegisub/blob/60eae86e21557340dcc0ae45719869e1bac9e4fa/src/audio_timing_dialogue.cpp#L698
但目前的拖动提交时，多个时间值（视频下方，字幕列表，字母编辑框上方）均会实时更新。在目前本人未见明显性能问题的情况下，我不建议修改此行为。
可能的方案包括但不限于：
* 将自动提交由两态改为三态：不提交/自动提交/仅在松开时提交；
* 在拖动时仅置flag，在`EVT_IDLE`内提交（相当于在低优先级提交，并合并短时间内的多次提交请求）
个人倾向于上述后一方案。

由于本人时间关系，issue列表内所有标注enhancement的issue都可能不会在短期内实现。如果您愿意，可提交相关PR。

**Comment by wangqr** [comment]
I've done some profiling. It turns out that commiting the changes itself only takes ~14% of CPU usage, and is not the main cause of the lag. The ass is commited fast enough to handle all mouse events.

The reason for the lag may be in `BaseGrid::OnPaint`. wxWidgets repaint changed areas in `EVT_PAINT`, and repainting BaseGrid takes much longer than repainting AudioDisplay, and will cause FPS drop (to ~15FPS on i7-8750H, Windows, Energy save mode) and produce the laggy feel.

**Comment by wangqr** [comment]
在 e481d033cbf4ffec105f17c84cb43480fc554ffd 中，我尝试将`BaseGrid::OnPaint`移至`OnIdle`内进行。

如果方便的话，可以试用一下r9137，看看情况是否改善： https://ftp.wangqr.tk/aegisub/aegisub-win64-cmake-20200606-r9137.zip

**Comment by The-Asgore** [comment]
As I tried r9137, although the lag still exists, it is very small and hard to be aware of. I think now the "Auto commit" future works well and smooth enough that doesn't affect normal use.
