### ISSUE TITLE
请求libass更新

### ISSUE THREAD

**Issue by vxzms** [wangqr/Aegisub#76]
libass 版本更新到了 [0.15.0](https://github.com/libass/libass/releases/tag/0.15.0)，希望开发者也能对 Aegisub 的 libass 组件进行更新

**Comment by MadokaAyukawa** [comment]
I would be interested in this as well. I noticed a few months back that the newest build of FFmpeg have a line spacing distance that is similar to VSFilter, and tighter spacing in 0,14 libass no longer render correctly in the new FFmpeg. I don't know if this is due to the new libass, but it would be nice to have the latest as an option.

**Comment by wangqr** [comment]
The next windows build will likely use [vcpkg](https://github.com/microsoft/vcpkg). It would be great if you can submit a PR there to upgrade the [libass port](https://github.com/microsoft/vcpkg/tree/master/ports/libass).

**Comment by vxzms** [comment]
https://github.com/microsoft/vcpkg/commit/cc4475d492bd1147f18e19f2c80b083a56391e18

**Comment by wangqr** [comment]
The new 3.3.2 build is using libass 0.15.0. It partially uses vcpkg but non-vcpkg dependencies can still be used.
